/**
 * Curated peak-rating anchors for well-known players, used by rebuildRatings.mjs to pin the top
 * of the rating scale. Every number here is a PitchSide-original estimate, independently derived
 * from general public knowledge of each player's reputation and career trajectory — the same
 * provenance rule as src/data/legends.ts. Never copied from FIFA, Football Manager, or any other
 * proprietary ratings database.
 *
 * `anchor` = estimated career-peak overall (within the dataset's era, ~2011 onward).
 * Matching is by diacritic-insensitive name slug, so accents/apostrophes don't matter.
 */
export const CURATED_ANCHORS = [
  // --- All-era elite ---
  { name: 'Lionel Messi', anchor: 97 },
  { name: 'Cristiano Ronaldo', anchor: 96 },
  { name: 'Kylian Mbappe', anchor: 95 },
  { name: 'Kevin De Bruyne', anchor: 93 },
  { name: 'Robert Lewandowski', anchor: 93 },
  { name: 'Neymar', anchor: 93 },
  { name: 'Erling Haaland', anchor: 93 },
  { name: 'Andres Iniesta', anchor: 93 },
  { name: 'Luka Modric', anchor: 92 },
  { name: 'Mohamed Salah', anchor: 92 },
  { name: 'Harry Kane', anchor: 92 },
  { name: 'Karim Benzema', anchor: 92 },
  { name: 'Luis Suarez', anchor: 92 },
  { name: 'Zlatan Ibrahimovic', anchor: 92 },
  { name: 'Eden Hazard', anchor: 92 },
  { name: 'Xavi', anchor: 92 },
  { name: 'Vinicius Junior', anchor: 92 },

  // --- Goalkeepers ---
  { name: 'Manuel Neuer', anchor: 93 },
  { name: 'Thibaut Courtois', anchor: 91 },
  { name: 'Alisson', anchor: 91 },
  { name: 'Alisson Becker', anchor: 91 },
  { name: 'Jan Oblak', anchor: 91 },
  { name: 'Gianluigi Buffon', anchor: 91 },
  { name: 'Iker Casillas', anchor: 91 },
  { name: 'Marc-Andre ter Stegen', anchor: 90 },
  { name: 'David de Gea', anchor: 90 },
  { name: 'Ederson', anchor: 89 },
  { name: 'Petr Cech', anchor: 89 },
  { name: 'Gianluigi Donnarumma', anchor: 89 },
  { name: 'Keylor Navas', anchor: 88 },
  { name: 'Hugo Lloris', anchor: 88 },
  { name: 'Samir Handanovic', anchor: 87 },
  { name: 'Emiliano Martinez', anchor: 87 },
  { name: 'Mike Maignan', anchor: 88 },
  { name: 'Joe Hart', anchor: 85 },
  { name: 'Kasper Schmeichel', anchor: 85 },
  { name: 'Wojciech Szczesny', anchor: 86 },
  { name: 'Kepa Arrizabalaga', anchor: 82 },
  { name: 'Jordan Pickford', anchor: 84 },
  { name: 'Nick Pope', anchor: 83 },
  { name: 'Aaron Ramsdale', anchor: 82 },

  // --- Defenders ---
  { name: 'Virgil van Dijk', anchor: 91 },
  { name: 'Sergio Ramos', anchor: 91 },
  { name: 'Philipp Lahm', anchor: 91 },
  { name: 'Thiago Silva', anchor: 91 },
  { name: 'Giorgio Chiellini', anchor: 90 },
  { name: 'Gerard Pique', anchor: 90 },
  { name: 'Nemanja Vidic', anchor: 90 },
  { name: 'Dani Alves', anchor: 90 },
  { name: 'Diego Godin', anchor: 89 },
  { name: 'Mats Hummels', anchor: 89 },
  { name: 'Vincent Kompany', anchor: 89 },
  { name: 'Marcelo', anchor: 89 },
  { name: 'Leonardo Bonucci', anchor: 89 },
  { name: 'John Terry', anchor: 89 },
  { name: 'Rio Ferdinand', anchor: 89 },
  { name: 'Jerome Boateng', anchor: 88 },
  { name: 'Kalidou Koulibaly', anchor: 88 },
  { name: 'David Alaba', anchor: 88 },
  { name: 'Ruben Dias', anchor: 88 },
  { name: 'Marquinhos', anchor: 88 },
  { name: 'Trent Alexander-Arnold', anchor: 88 },
  { name: 'Joshua Kimmich', anchor: 90 },
  { name: 'Achraf Hakimi', anchor: 87 },
  { name: 'Joao Cancelo', anchor: 87 },
  { name: 'Andrew Robertson', anchor: 87 },
  { name: 'Antonio Rudiger', anchor: 87 },
  { name: 'Dani Carvajal', anchor: 87 },
  { name: 'Theo Hernandez', anchor: 87 },
  { name: 'Alphonso Davies', anchor: 86 },
  { name: 'Raphael Varane', anchor: 88 },
  { name: 'Milan Skriniar', anchor: 86 },
  { name: 'Jordi Alba', anchor: 87 },
  { name: 'Cesar Azpilicueta', anchor: 85 },
  { name: 'Kyle Walker', anchor: 85 },
  { name: 'John Stones', anchor: 85 },
  { name: 'William Saliba', anchor: 87 },
  { name: 'Gabriel Magalhaes', anchor: 85 },
  { name: 'Ashley Cole', anchor: 88 },
  { name: 'Patrice Evra', anchor: 87 },
  { name: 'Branislav Ivanovic', anchor: 85 },
  { name: 'Gary Cahill', anchor: 83 },
  { name: 'David Luiz', anchor: 84 },
  { name: 'Pepe', anchor: 88 },
  { name: 'Javier Mascherano', anchor: 88 },
  { name: 'Bastian Schweinsteiger', anchor: 89 },

  // --- Midfielders ---
  { name: 'Toni Kroos', anchor: 91 },
  { name: 'Rodri', anchor: 91 },
  { name: 'Andrea Pirlo', anchor: 91 },
  { name: 'Sergio Busquets', anchor: 90 },
  { name: 'David Silva', anchor: 90 },
  { name: 'Steven Gerrard', anchor: 89 },
  { name: "N'Golo Kante", anchor: 89 },
  { name: 'Jude Bellingham', anchor: 90 },
  { name: 'Frank Lampard', anchor: 88 },
  { name: 'Yaya Toure', anchor: 88 },
  { name: 'Mesut Ozil', anchor: 89 },
  { name: 'Cesc Fabregas', anchor: 88 },
  { name: 'Paul Pogba', anchor: 88 },
  { name: 'Casemiro', anchor: 88 },
  { name: 'Federico Valverde', anchor: 88 },
  { name: 'Pedri', anchor: 88 },
  { name: 'Bruno Fernandes', anchor: 88 },
  { name: 'Bernardo Silva', anchor: 88 },
  { name: 'Florian Wirtz', anchor: 89 },
  { name: 'Jamal Musiala', anchor: 88 },
  { name: 'Martin Odegaard', anchor: 87 },
  { name: 'Declan Rice', anchor: 87 },
  { name: 'Phil Foden', anchor: 88 },
  { name: 'Ilkay Gundogan', anchor: 87 },
  { name: 'Marco Verratti', anchor: 87 },
  { name: 'Thiago', anchor: 87 },
  { name: 'Thiago Alcantara', anchor: 87 },
  { name: 'Christian Eriksen', anchor: 87 },
  { name: 'Ivan Rakitic', anchor: 86 },
  { name: 'Arturo Vidal', anchor: 87 },
  { name: 'Fernandinho', anchor: 86 },
  { name: 'Jordan Henderson', anchor: 84 },
  { name: 'Fabinho', anchor: 86 },
  { name: 'Georginio Wijnaldum', anchor: 85 },
  { name: 'James Milner', anchor: 82 },
  { name: 'Nicolo Barella', anchor: 87 },
  { name: 'Sandro Tonali', anchor: 86 },
  { name: 'Michael Carrick', anchor: 85 },
  { name: 'Nemanja Matic', anchor: 85 },
  { name: 'Luka Jovic', anchor: 78 },
  { name: 'Mateo Kovacic', anchor: 85 },
  { name: 'Aaron Ramsey', anchor: 84 },
  { name: 'Santi Cazorla', anchor: 86 },
  { name: 'Juan Mata', anchor: 86 },
  { name: 'Oscar', anchor: 84 },
  { name: 'Willian', anchor: 84 },
  { name: 'Ross Barkley', anchor: 79 },
  { name: 'Danny Drinkwater', anchor: 78 },
  { name: 'Tiemoue Bakayoko', anchor: 77 },
  { name: 'Jorginho', anchor: 85 },
  { name: 'Moises Caicedo', anchor: 86 },
  { name: 'Enzo Fernandez', anchor: 85 },
  { name: 'Alexis Mac Allister', anchor: 86 },
  { name: 'Dominik Szoboszlai', anchor: 85 },
  { name: 'Cole Palmer', anchor: 88 },
  { name: 'Bukayo Saka', anchor: 88 },
  { name: 'Vitinha', anchor: 87 },
  { name: 'Joao Neves', anchor: 86 },

  // --- Forwards / wingers ---
  { name: 'Gareth Bale', anchor: 90 },
  { name: 'Antoine Griezmann', anchor: 90 },
  { name: 'Sergio Aguero', anchor: 91 },
  { name: 'Arjen Robben', anchor: 91 },
  { name: 'Franck Ribery', anchor: 91 },
  { name: 'Wayne Rooney', anchor: 90 },
  { name: 'Robin van Persie', anchor: 90 },
  { name: 'Edinson Cavani', anchor: 90 },
  { name: 'Gonzalo Higuain', anchor: 89 },
  { name: 'Radamel Falcao', anchor: 89 },
  { name: 'Angel Di Maria', anchor: 89 },
  { name: 'Sadio Mane', anchor: 89 },
  { name: 'Son Heung-min', anchor: 89 },
  { name: 'Thomas Muller', anchor: 89 },
  { name: 'Ousmane Dembele', anchor: 89 },
  { name: 'Paulo Dybala', anchor: 88 },
  { name: 'Pierre-Emerick Aubameyang', anchor: 88 },
  { name: 'Romelu Lukaku', anchor: 87 },
  { name: 'Victor Osimhen', anchor: 88 },
  { name: 'Lautaro Martinez', anchor: 88 },
  { name: 'Khvicha Kvaratskhelia', anchor: 88 },
  { name: 'Lamine Yamal', anchor: 91 },
  { name: 'Raphinha', anchor: 88 },
  { name: 'Rodrygo', anchor: 87 },
  { name: 'Diego Costa', anchor: 88 },
  { name: 'Carlos Tevez', anchor: 88 },
  { name: 'Alexis Sanchez', anchor: 87 },
  { name: 'Roberto Firmino', anchor: 87 },
  { name: 'Raheem Sterling', anchor: 87 },
  { name: 'Riyad Mahrez', anchor: 87 },
  { name: 'Ciro Immobile', anchor: 87 },
  { name: 'Isak', anchor: 87 },
  { name: 'Alexander Isak', anchor: 87 },
  { name: 'Jamie Vardy', anchor: 86 },
  { name: 'Lorenzo Insigne', anchor: 86 },
  { name: 'Dries Mertens', anchor: 86 },
  { name: 'Marcus Rashford', anchor: 85 },
  { name: 'Jack Grealish', anchor: 85 },
  { name: 'Gabriel Jesus', anchor: 85 },
  { name: 'Kai Havertz', anchor: 85 },
  { name: 'Leroy Sane', anchor: 87 },
  { name: 'Serge Gnabry', anchor: 86 },
  { name: 'Kingsley Coman', anchor: 86 },
  { name: 'Christopher Nkunku', anchor: 85 },
  { name: 'Olivier Giroud', anchor: 84 },
  { name: 'Alvaro Morata', anchor: 84 },
  { name: 'Timo Werner', anchor: 82 },
  { name: 'Darwin Nunez', anchor: 82 },
  { name: 'Ollie Watkins', anchor: 84 },
  { name: 'Viktor Gyokeres', anchor: 86 },
  { name: 'Michy Batshuayi', anchor: 77 },
  { name: 'Didier Drogba', anchor: 89 },
  { name: 'Fernando Torres', anchor: 86 },
  { name: 'Daniel Sturridge', anchor: 84 },
  { name: 'Philippe Coutinho', anchor: 87 },
  { name: 'Dimitri Payet', anchor: 86 },
  { name: 'Hatem Ben Arfa', anchor: 83 },
  { name: 'Memphis Depay', anchor: 85 },
  { name: 'Wissam Ben Yedder', anchor: 84 },
  { name: 'Moussa Dembele', anchor: 80 },
  { name: 'Jonathan David', anchor: 85 },
  { name: 'Bradley Barcola', anchor: 85 },
  { name: 'Desire Doue', anchor: 86 },
  { name: 'Marco Reus', anchor: 88 },
  { name: 'Mario Gotze', anchor: 86 },
  { name: 'Julian Brandt', anchor: 84 },
  { name: 'Patrik Schick', anchor: 83 },
  { name: 'Karim Adeyemi', anchor: 83 },
  { name: 'Michael Olise', anchor: 88 },
  { name: 'Luis Diaz', anchor: 87 },
  { name: 'Serhou Guirassy', anchor: 85 },
  { name: 'Aleksandar Mitrovic', anchor: 84 },
  { name: 'Moussa Diaby', anchor: 84 },
  { name: 'Jean-Philippe Mateta', anchor: 82 },
  { name: 'Yussuf Poulsen', anchor: 79 },
  { name: 'Papiss Cisse', anchor: 80 },
  { name: 'Eberechi Eze', anchor: 85 },
  { name: 'Anthony Gordon', anchor: 84 },
  { name: 'Matheus Cunha', anchor: 84 },
  { name: 'Bryan Mbeumo', anchor: 84 },
  { name: 'Nicolas Jackson', anchor: 81 },
  { name: 'Benjamin Sesko', anchor: 84 },
  { name: 'Loïs Openda', anchor: 84 },
  { name: 'Randal Kolo Muani', anchor: 84 },
  { name: 'Marcus Thuram', anchor: 85 },
  { name: 'Ademola Lookman', anchor: 85 },
  { name: 'Mario Mandzukic', anchor: 86 },
  { name: 'Edin Dzeko', anchor: 87 },
  { name: 'Duvan Zapata', anchor: 84 },
  { name: 'Josip Ilicic', anchor: 84 },
  { name: 'Papu Gomez', anchor: 85 },
  { name: 'Fabio Quagliarella', anchor: 84 },
  { name: 'Arkadiusz Milik', anchor: 82 },
  { name: 'Andrej Kramaric', anchor: 84 },
  { name: 'Max Kruse', anchor: 83 },
  { name: 'Vedad Ibisevic', anchor: 80 },
  { name: 'Iago Aspas', anchor: 86 },
  { name: 'Gerard Moreno', anchor: 85 },
  { name: 'Mikel Oyarzabal', anchor: 86 },
  { name: 'Nabil Fekir', anchor: 85 },
  { name: 'Florian Thauvin', anchor: 85 },
  { name: 'Alassane Plea', anchor: 82 },
  { name: 'Teji Savanier', anchor: 81 },
  { name: 'Gaetan Laborde', anchor: 80 },
  { name: 'Jadon Sancho', anchor: 87 },
  { name: 'Theo Walcott', anchor: 84 },
  { name: 'Henrikh Mkhitaryan', anchor: 86 },
  { name: 'Marcel Sabitzer', anchor: 84 },
  { name: 'Shinji Kagawa', anchor: 85 },
  { name: 'Thorgan Hazard', anchor: 82 },
  { name: 'Anthony Martial', anchor: 84 },
  { name: 'Javier Hernandez', anchor: 84 },
  { name: 'Kevin Volland', anchor: 83 },
  { name: 'Leon Bailey', anchor: 84 },
  { name: 'Leon Goretzka', anchor: 86 },
  { name: 'Ivan Perisic', anchor: 86 },
  { name: 'Axel Witsel', anchor: 85 },
  { name: 'Donyell Malen', anchor: 83 },
  { name: 'Andre Silva', anchor: 82 },
  { name: 'Inaki Williams', anchor: 84 },
  { name: 'Koke', anchor: 86 },
  { name: 'Raul Garcia', anchor: 83 },
  { name: 'Angel Correa', anchor: 84 },
  { name: 'Yannick Carrasco', anchor: 85 },
  { name: 'Alexander Sorloth', anchor: 84 },
  { name: 'Julian Alvarez', anchor: 89 },
  { name: 'Ansu Fati', anchor: 82 },
  { name: 'Nolito', anchor: 82 },
  { name: 'Anthony Modeste', anchor: 81 },
  { name: 'Lucas Alario', anchor: 80 },
  { name: 'Christoph Baumgartner', anchor: 82 },
  { name: 'Brais Mendez', anchor: 81 },
  { name: 'Rodrigo', anchor: 85 },
  { name: 'Carlos Bacca', anchor: 85 },
  { name: 'Kevin Gameiro', anchor: 84 },
  { name: 'Youssef En-Nesyri', anchor: 84 },
  { name: 'Lucas Ocampos', anchor: 84 },
  { name: 'Isco', anchor: 87 },
  { name: 'Goncalo Guedes', anchor: 83 },
  { name: 'Cedric Bakambu', anchor: 83 },
  { name: 'Lukas Podolski', anchor: 85 },
  { name: 'Stefan Kiessling', anchor: 84 },
  { name: 'Jakub Blaszczykowski', anchor: 84 },
  { name: 'Paco Alcacer', anchor: 83 },
  { name: 'Adrian', anchor: 80 },
];

/** Diacritic-insensitive, punctuation-insensitive name key for anchor matching. */
export function nameKey(name) {
  return name
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    // Letters with no NFD decomposition (ø, ł, ß, ...) must be transliterated explicitly or
    // they get stripped entirely and the key silently stops matching.
    .replace(/ø/g, 'o').replace(/ł/g, 'l').replace(/ß/g, 'ss').replace(/đ/g, 'd')
    .replace(/æ/g, 'ae').replace(/œ/g, 'oe').replace(/ð/g, 'd').replace(/þ/g, 'th')
    .replace(/[^a-z0-9]/g, '');
}

export function buildAnchorMap() {
  const map = new Map();
  for (const entry of CURATED_ANCHORS) {
    map.set(nameKey(entry.name), entry.anchor);
  }
  return map;
}
